### ISSUE TITLE
Italics used as sub-section headers

### ISSUE THREAD

**Issue by ericherman** [publiccodenet/process-code-software-procurement-old#19]
Consider replacing italics with lower-depth (h4) subsection headings:

for instance, [Phase 1a](https://raw.githubusercontent.com/publiccodenet/process-code-software-procurement/gh-pages/_phases/02.md) contains:

> _Reaching out to individuals and departments:_
> _Building basic familiarity with software and software procurement:_
> _Training and designating product owners:_

and others headings which look like sub-section headings

**Comment by Ainali** [comment]
Yes, and if the current h4 style isn't nice enough, let's work on that in the style sheet instead.
